Use wrapper pillow to generate the images
rodorgas/citadorbot pull request #11
Opened 2020-10-08 19:45 UTC by luiz-meireles

This pull request is to initially validate the new way of creating the images.

2020-10-08 19:49 UTC, luiz-meireles commented
I forgot to add pillow dependence in the requirements

2020-10-09 20:16 UTC, luiz-meireles commented
I'm working in some improvements related to the text generation.

2020-10-11 01:28 UTC, luiz-meireles commented
I'm fixing layout problems.

2020-10-13 00:41 UTC, rodorgas commented
Thanks for contributing! Removing the imagemagick dependency is amazing and requires a lot of code, thanks for the effort!

I'm having trouble running on my system, though. The keyword `embedded_color` [doesn't seem to exist](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html?highlight=multiline_text#PIL.ImageDraw.ImageDraw.multiline_text) on the latest stable version (7.2.0) of the Pillow's `ImageDraw.multiline_text` function. Maybe you're using an outdated version? I installed it from `requirements.txt`.

```
bot.py:158: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(TOKEN)
quote rodorgas
2020-10-12 21:17:23,228 - __main__ - WARNING - Update "..." caused error "multiline_text() got an unexpected keyword argument 'embedded_color'"
```

2020-10-19 00:16 UTC, rodorgas requested changes

2020-10-19 00:16 UTC, rodorgas commented on make_image.py
> +        img_context = text_image(
E quando for `/quote` sem contexto? Talvez precise de um condicional aqui.

2020-10-19 00:16 UTC, rodorgas commented on make_image.py
> +        img_context = text_image(
Recebo o erro `caused error "'NoneType' object has no attribute 'expandtabs'` ao rodar um `/quote`, acredito que esteja relacionado.

2020-10-19 03:17 UTC, closed without merging

2020-10-19 03:18 UTC, luiz-meireles commented
I will open a new clean pull request